### PR TITLE
Experiment2

### PR DESCRIPTION
**Pull request by mudspringhiker**
test pull request

### CODE REVIEW

**Comment by scichelli** [comment]
@mudspringhiker Thanks for playing along! :) Since I merged Randi's commits, `scichelli:master` contains history that your branch here doesn't have, and GitHub is warning you about that conflict. If you would like to try resolving the conflict, I'm happy to answer any questions. As a hint, you need to "pull" from the "upstream" remote into your local `master`, resolve any conflicts, merge from your `master` into your `experiment2` branch, and push to the "origin" remote. Want to try it out?

**Comment by mudspringhiker** [comment]
@scichelli did everything you said (pulled from upstream to my local, I didn't have any conflicts, merged master with my experiment2 branch and pushed to origin remote). not sure what's next. What happens to the pull request I did? Thanks!

**Comment by scichelli** [comment]
@mudspringhiker  The result of all that is that GitHub now says this PR is ready to merge. Perfect! I'll merge it now.

The result of your updates to your branch:
image

**Comment by scichelli** [comment]
If you take a look at the list of commits on my version of the repo, you will see where I merged this PR in. And because I did not "squash" it, but instead used the option that creates a merge commit, all of your individual commits are in that history, too.

History:
https://github.com/scichelli/wids-github-exercises/commits/master

**Comment by mudspringhiker** [comment]
Oh cool! Thank you very much! I have only used git to do my own versioning
but rarely used it for collaboration. Thank you!

**Comment by scichelli** [comment]
Happy to. :) And if you want to try other experiments, feel free to use this repo as a scratch space. Oh hey, I just had an idea... I can create a PR targeting _your_ fork of the repo.

**Comment by mudspringhiker** [comment]
Thanks again! I will try that.

**Pull request merged**
